services:
  db:
    env_file:
      - .env
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    command: redis-server --save 60 1 --loglevel warning
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  web:
    build:
      args:
        CONTAINER_GID: ${CONTAINER_GID:-1000}
        CONTAINER_UID: ${CONTAINER_UID:-1000}
        CONTAINER_USER: ${CONTAINER_USER:-rails}
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "3000:3000"
    tmpfs:
      - /rails/tmp,gid=${CONTAINER_GID},uid=${CONTAINER_UID}
      - /tmp,gid=${CONTAINER_GID},uid=${CONTAINER_UID}
    volumes:
      - type: bind
        source: .
        target: /rails
volumes:
  db_data: {}
  redis_data: {}
